name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"

jobs:
  release:
    uses: Themekraft/release-tooling/.github/workflows/release.yml@main
    with:
      slug: buddyforms-pay-for-submissions
      freemius-id: "5792"
      main-file: buddyforms-pay-for-submissions.php
      wporg: false
    secrets: inherit
